### ISSUE TITLE
When will cvxpy come with python 3.11 support?

### ISSUE THREAD

**Issue by Wongboo** [conda-forge/cvxpy-feedstock#78]
### Comment:

Since v1.3.0 cvxpy support support python 3.11, when will cvxpy come with python 3.11 support? 
I'm willing to provide some help about it, but I had to admit that I'm not familiar with conda-forge contributing system.

**Comment by h-vetinari** [comment]
We're stuck on needing to wait for osqp, which does not support python 3.11 due to use of scipy APIs that were removed in 1.9 (and 1.10 is the first version supporting python 3.11). Fixing this has stalled because we need some help from upstream, which has been open for a while: https://github.com/osqp/osqp/issues/497
